"""add_maintenance_ticket_table

Revision ID: 05864b2cbb33
Revises: 70637ae29f36
Create Date: 2026-07-24 16:54:47.317528

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05864b2cbb33'
down_revision = '70637ae29f36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('maintenance_ticket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pc_id', sa.Integer(), nullable=False),
    sa.Column('reporter', sa.String(length=50), nullable=False),
    sa.Column('kategori', sa.String(length=30), nullable=False),
    sa.Column('prioritas', sa.String(length=10), nullable=True),
    sa.Column('judul', sa.String(length=150), nullable=False),
    sa.Column('deskripsi', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('resolusi', sa.Text(), nullable=True),
    sa.Column('biaya', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_by', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['pc_id'], ['pc.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('maintenance_ticket')
    # ### end Alembic commands ###
