"""add serial monitoring to hardware

Revision ID: 1daeed34ce74
Revises: 64353b63b438
Create Date: 2026-07-12 17:01:14.420784

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1daeed34ce74'
down_revision = '64353b63b438'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hardware_monitor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hardware_baseline', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('hardware_current_specs', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('hardware_mismatch', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('hardware_mismatch_desc', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('hardware_mismatch_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('hardware_last_sync', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hardware_monitor', schema=None) as batch_op:
        batch_op.drop_column('hardware_last_sync')
        batch_op.drop_column('hardware_mismatch_time')
        batch_op.drop_column('hardware_mismatch_desc')
        batch_op.drop_column('hardware_mismatch')
        batch_op.drop_column('hardware_current_specs')
        batch_op.drop_column('hardware_baseline')

    # ### end Alembic commands ###
