"""add_pc_uptime_log_table

Revision ID: 326a351f8a88
Revises: 05864b2cbb33
Create Date: 2026-07-28 19:05:51.754071

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
"""add_pc_uptime_log_table

Revision ID: 326a351f8a88
Revises: 05864b2cbb33
Create Date: 2026-07-28 19:05:51.754071

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '326a351f8a88'
down_revision = '05864b2cbb33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    if not sa.inspect(op.get_bind()).has_table('pc_uptime_log'):
        op.create_table('pc_uptime_log',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('pc_id', sa.Integer(), nullable=False),
        sa.Column('tanggal', sa.Date(), nullable=False),
        sa.Column('total_online_seconds', sa.Integer(), nullable=False),
        sa.Column('total_billing_seconds', sa.Integer(), nullable=False),
        sa.Column('first_seen', sa.DateTime(), nullable=True),
        sa.Column('last_seen', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['pc_id'], ['pc.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('pc_id', 'tanggal', name='uq_pc_uptime_pc_tanggal')
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    if sa.inspect(op.get_bind()).has_table('pc_uptime_log'):
        op.drop_table('pc_uptime_log')
    # ### end Alembic commands ###
