"""add_process_monitoring

Revision ID: 433a9f697a02
Revises: 
Create Date: 2026-04-14 23:15:15.020630

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '433a9f697a02'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hardware_monitor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active_window', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hardware_monitor', schema=None) as batch_op:
        batch_op.drop_column('active_window')

    # ### end Alembic commands ###
