"""add_tunai_kembalian_to_transaksi_menu

Revision ID: 434a73db84b5
Revises: 433a9f697a02
Create Date: 2026-06-16 16:03:53.217598

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '434a73db84b5'
down_revision = '433a9f697a02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaksi_menu', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tunai', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('kembalian', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaksi_menu', schema=None) as batch_op:
        batch_op.drop_column('kembalian')
        batch_op.drop_column('tunai')

    # ### end Alembic commands ###
