"""add payment method columns

Revision ID: 638015476514
Revises: fd5f342fef7d
Create Date: 2026-07-13 18:16:53.272473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '638015476514'
down_revision = 'fd5f342fef7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaksi', schema=None) as batch_op:
        batch_op.add_column(sa.Column('metode_pembayaran', sa.String(length=50), nullable=True))

    # Backfill existing transaksi to 'Tunai'
    op.execute("UPDATE transaksi SET metode_pembayaran = 'Tunai' WHERE metode_pembayaran IS NULL")

    with op.batch_alter_table('transaksi_menu', schema=None) as batch_op:
        batch_op.add_column(sa.Column('metode_pembayaran', sa.String(length=50), nullable=True))

    # Backfill existing transaksi_menu to 'Tunai'
    op.execute("UPDATE transaksi_menu SET metode_pembayaran = 'Tunai' WHERE metode_pembayaran IS NULL")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaksi_menu', schema=None) as batch_op:
        batch_op.drop_column('metode_pembayaran')

    with op.batch_alter_table('transaksi', schema=None) as batch_op:
        batch_op.drop_column('metode_pembayaran')

    # ### end Alembic commands ###
