"""add_mikrotik_config

Revision ID: 64353b63b438
Revises: f2002facdcac
Create Date: 2026-06-27 23:50:34.524138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64353b63b438'
down_revision = 'f2002facdcac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mikrotik_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('host', sa.String(length=100), nullable=True),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('hotspot_profile', sa.String(length=100), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mikrotik_config')
    # ### end Alembic commands ###
