"""add pos_x pos_y to pc

Revision ID: f2002facdcac
Revises: 378524089e68
Create Date: 2026-06-19 01:30:24.224286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2002facdcac'
down_revision = '378524089e68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pc', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pos_x', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('pos_y', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pc', schema=None) as batch_op:
        batch_op.drop_column('pos_y')
        batch_op.drop_column('pos_x')

    # ### end Alembic commands ###
